# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 22:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20160620_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
