# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20160621_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_room',
            name='color',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Color'),
        ),
    ]
