# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20160621_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_user',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
