# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Color'),
        ),
    ]
