# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
