# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_room',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
